# -*- coding: UTF-8 -*-
"""
var all = document.querySelectorAll("#mw-content-text tr>td:first-child>a");
var data = [];
for(var i in all) {
  if (all[i].title) {
    data.push(all[i].title);
  }
}

data = data.filter(function(item, pos) {
    return data.indexOf(item) == pos;
})
"""

UNIQUE_LIST = [
  "The Anvil",
  "Araku Tiki",
  "Astramentis",
  "Atziri's Foible",
  "The Aylardex",
  "Blightwell",
  "Blood of Corruption",
  "Bloodgrip",
  "Carnage Heart",
  "Daresso's Salute",
  "Demigod's Presence",
  "Extractor Mentis",
  "Eye of Chayula",
  "Eyes of the Greatwolf",
  "The Ignomon",
  "Karui Ward",
  "Marylene's Fallacy",
  "Natural Hierarchy",
  "Night's Hold",
  "Rashkaldor's Patience",
  "Rigwald's Curse",
  "Shaper's Seed",
  "Sidhebreath",
  "Stone of Lazhwar",
  "Talisman of the Victor",
  "Tear of Purity",
  "Ungil's Harmony",
  "Victario's Acuity",
  "Voll's Devotion",
  "Warped Timepiece",
  "Winterheart",
  "Auxium",
  "Bated Breath",
  "Belt of the Deceiver",
  "Demigod's Bounty",
  "Doryani's Invitation",
  "Dyadian Dawn",
  "Faminebind",
  "Feastbind",
  "Headhunter",
  "Immortal Flesh",
  "The Magnate",
  "Maligaro's Restraint",
  "Meginord's Girdle",
  "Perandus Blazon",
  "Prismweave",
  "The Retch",
  "Soulthirst",
  "Sunblast",
  "Wurm's Molt",
  "Andvarius",
  "Berek's Grip",
  "Berek's Pass",
  "Berek's Respite",
  "Blackheart",
  "Bloodboil",
  "Brinerot Mark",
  "Call of the Brotherhood",
  "Death Rush",
  "Demigod's Eye",
  "Doedre's Damning",
  "Dream Fragments",
  "Emberwake",
  "Gifts from Above",
  "Heartbound Loop",
  "Kaom's Sign",
  "Kikazaru",
  "Le Heup of All",
  "Lori's Lantern",
  "Malachai's Artifice",
  "Ming's Heart",
  "Mokou's Embrace",
  "Mutewind Seal",
  "Ngamahu's Sign",
  "The Pariah",
  "Perandus Signet",
  "Pyre",
  "Redblade Band",
  "Rigwald's Crest",
  "Romira's Banquet",
  "Shavronne's Revelation",
  "Sibyl's Lament",
  "The Taming",
  "Tasalio's Sign",
  "Thief's Torment",
  "Timeclasp",
  "Valako's Sign",
  "Ventor's Gamble",
  "Voideye",
  "Asphyxia's Wrath",
  "Blackgleam",
  "Craghead",
  "Drillneck",
  "Hyrri's Bite",
  "Maloney's Nightfall",
  "Rearguard",
  "Rigwald's Quills",
  "Soul Strike",
  "Broadstroke",
  "Bramblejack",
  "Death's Oath",
  "Greed's Embrace",
  "Kaom's Heart",
  "Lioneye's Vision",
  "Solaris Lorica",
  "Ashrend",
  "Briskwrap",
  "Bronn's Lithe",
  "Foxshade",
  "Hyrri's Ire",
  "Queen of the Forest",
  "The Rat Cage",
  "Cloak of Flame",
  "The Covenant",
  "Infernal Mantle",
  "Shavronne's Wrappings",
  "Soul Mantle",
  "Tabula Rasa",
  "Vis Mortis",
  "Zahndethus' Cassock",
  "Belly of the Beast",
  "Cherrubim's Maleficence",
  "Daresso's Defiance",
  "Lightning Coil",
  "Ambu's Charge",
  "Icetomb",
  "Incandescent Heart",
  "Kingsguard",
  "Lightbane Raiment",
  "Voll's Protector",
  "Carcass Jack",
  "Cloak of Defiance",
  "The Restless Ward",
  "Thousand Ribbons",
  "Victario's Influence",
  "Atziri's Splendour",
  "Demigod's Dominance",
  "Kaom's Roots",
  "Redblade Tramplers",
  "Windscream",
  "Atziri's Step",
  "The Blood Dance",
  "Deerstalker",
  "Goldwyrm",
  "Victario's Flight",
  "Bones of Ullr",
  "Rainbowstride",
  "Shavronne's Pace",
  "Skyforth",
  "Steppan Eard",
  "Wanderlust",
  "Wondertrap",
  "Darkray Vectors",
  "Dusktoe",
  "Lioneye's Paws",
  "Mutewind Whispersteps",
  "Alberon's Warpath",
  "Gang's Momentum",
  "Wake of Destruction",
  "Brinerot Whalers",
  "Nomic's Storm",
  "Sin Trek",
  "Sundance",
  "Demigod's Stride",
  "Atziri's Acuity",
  "Doryani's Fist",
  "Empire's Grasp",
  "Lochtonial Caress",
  "Meginord's Vise",
  "Winds of Change",
  "Hrimsorrow",
  "Maligaro's Virtuosity",
  "Asenath's Gentle Touch",
  "Doedre's Tenure",
  "Sadima's Touch",
  "Voidbringer",
  "Aurseize",
  "Flesh and Spirit",
  "Slitherpinch",
  "Surgebinders",
  "Vaal Caress",
  "Null and Void",
  "Repentance",
  "Shackles of the Wretched",
  "Southbound",
  "Facebreaker",
  "Ondar's Clasp",
  "Shadows and Dust",
  "Snakebite",
  "Thunderfist",
  "Demigod's Touch",
  "Abyssus",
  "Ezomyte Peak",
  "Hrimnor's Resolve",
  "Alpha's Howl",
  "Fairgraves' Tricorne",
  "Goldrim",
  "Heatshiver",
  "Rat's Nest",
  "Starkonja's Head",
  "Asenath's Mark",
  "Chitus' Apex",
  "Crown of Eyes",
  "Crown of Thorns",
  "Doedre's Scorn",
  "Rime Gaze",
  "Scold's Bridle",
  "Ylfeban's Trickery",
  "Black Sun Crest",
  "The Bringer of Rain",
  "Deidbell",
  "Devoto's Devotion",
  "The Peregrine",
  "Skullhead",
  "The Broken Crown",
  "Geofri's Crest",
  "Honourhome",
  "Mindspiral",
  "Veil of the Night",
  "Crown of the Pale King",
  "The Gull",
  "Leer Cast",
  "Malachai's Simula",
  "The Three Dragons",
  "The Vertex",
  "Demigod's Triumph",
  "Aegis Aurora",
  "Atziri's Mirror",
  "Brinerot Flag",
  "Broken Faith",
  "Chalice of Horrors",
  "Chernobog's Pillar",
  "Crest of Perandus",
  "Daresso's Courage",
  "Demigod's Beacon",
  "The Deep One's Hide",
  "Great Old One's Ward",
  "Jaws of Agony",
  "Kaltenhalt",
  "Kongming's Stratagem",
  "Lioneye's Remorse",
  "Maligaro's Lens",
  "Matua Tupuna",
  "Mutewind Pennant",
  "Prism Guardian",
  "Rathpith Globe",
  "Redblade Banner",
  "Rise of the Phoenix",
  "Saffell's Frame",
  "Sentari's Answer",
  "Springleaf",
  "Thousand Teeth Temu",
  "Titucius' Span",
  "Trolltimber Spire",
  "Wheel of the Stormsail",
  "Acton's Nightmare",
  "Caer Blaidd, Wolfpack's Den",
  "The Coward's Trial",
  "Death and Taxes",
  "Hall of Grandmasters",
  "Maelström of Chaos",
  "Mao Kun",
  "Oba's Cursed Trove",
  "Olmec's Sanctum",
  "Poorjoy's Asylum",
  "Vaults of Atziri",
  "The Vinktar Square",
  "Whakawairua Tuahu",
  "Anatomical Knowledge",
  "Apparitions",
  "Army of Bones",
  "Brawn",
  "Brute Force Solution",
  "Careful Planning",
  "Clear Mind",
  "Cold Steel",
  "Dead Reckoning",
  "Efficient Training",
  "Eldritch Knowledge",
  "Energised Armour",
  "Energy From Within",
  "Fertile Mind",
  "Fireborn",
  "Fluid Motion",
  "Fortified Legion",
  "Fragile Bloom",
  "Growing Agony",
  "Healthy Mind",
  "Hidden Potential",
  "Hotfooted",
  "Inertia",
  "Inspired Learning",
  "Intuitive Leap",
  "Izaro's Turmoil",
  "Lioneye's Fall",
  "Malicious Intent",
  "Mantra of Flames",
  "Martial Artistry",
  "Might in All Forms",
  "Pitch Darkness",
  "Pugilist",
  "Rain of Splinters",
  "Rapid Expansion",
  "Rolling Flames",
  "Shattered Chains",
  "Spire of Stone",
  "Spirit Guards",
  "Spirited Response",
  "Static Electricity",
  "Steel Spirit",
  "The Vigil",
  "Volley Fire",
  "Weight of the Empire",
  "Winter's Bounty",
  "Ancient Waystones",
  "Atziri's Reign",
  "Blood Sacrifice",
  "Brittle Barrier",
  "Chill of Corruption",
  "Combustibles",
  "Corrupted Energy",
  "Fevered Mind",
  "Fragility",
  "Hungry Abyss",
  "Mutated Growth",
  "Pacifism",
  "Powerlessness",
  "Sacrificial Harvest",
  "Self-Flagellation",
  "Vaal Sentencing",
  "Weight of Sin",
  "Assassin's Haste",
  "Conqueror's Efficiency",
  "Conqueror's Longevity",
  "Conqueror's Potency",
  "Poacher's Aim",
  "Survival Instincts",
  "Survival Secrets",
  "Survival Skills",
  "Warlord's Reach",
  "Blood of the Karui",
  "Doedre's Elixir",
  "Lavianga's Spirit",
  "Zerphi's Last Breath",
  "Divination Distillate",
  "The Writhing Jar",
  "Atziri's Promise",
  "Coruscating Elixir",
  "Forbidden Taste",
  "Lion's Roar",
  "Rotgut",
  "Rumi's Concoction",
  "The Sorrow of the Divine",
  "Taste of Hate",
  "Dreadarc",
  "Dyadus",
  "Jack, the Axe",
  "Moonbender's Wing",
  "Relentless Fury",
  "Rigwald's Savagery",
  "The Screaming Eagle",
  "Soul Taker",
  "Atziri's Disfavour",
  "The Blood Reaper",
  "The Harvest",
  "Hezmana's Bloodlust",
  "Kaom's Primacy",
  "Kingmaker",
  "Limbsplit",
  "Reaper's Pursuit",
  "Wideswing",
  "Wings of Entropy",
  "Chin Sol",
  "Darkscorn",
  "Death's Harp",
  "Doomfletch",
  "Infractem",
  "Lioneye's Glare",
  "Null's Inclination",
  "Quill Rain",
  "Roth's Reach",
  "Silverbranch",
  "Storm Cloud",
  "Voltaxic Rift",
  "Windripper",
  "Al Dhih",
  "Allure",
  "Bloodseeker",
  "Cybil's Paw",
  "Essentia Sanguis",
  "Izaro's Dilemma",
  "Last Resort",
  "Mortem Morsu",
  "Ornament of the East",
  "Wildslash",
  "Bino's Kitchen Knife",
  "Bloodplay",
  "The Consuming Dark",
  "Divinarius",
  "Goredrill",
  "Heartbreaker",
  "Mark of the Doubting Knight",
  "Mightflay",
  "Ungil's Gauche",
  "Song of the Sirens",
  "Brightbeak",
  "Callinellus Malleus",
  "Cameria's Maul",
  "Flesh-Eater",
  "Gorebreaker",
  "Lavianga's Wisdom",
  "Mjölner",
  "Bitterdream",
  "Brutus' Lead Sprinkler",
  "The Dark Seer",
  "Death's Hand",
  "Doon Cuebiyari",
  "Doryani's Catalyst",
  "Mon'tregul's Grasp",
  "Nycta's Lantern",
  "Spine of the First Claimant",
  "The Supreme Truth",
  "Chober Chaber",
  "Geofri's Baptism",
  "Hrimnor's Hymn",
  "Jorrhast's Blacksteel",
  "Kongor's Undying Rage",
  "Marohi Erqi",
  "Quecholli",
  "Voidhome",
  "Dreamfeather",
  "Ephemeral Edge",
  "Hyaon's Fury",
  "The Goddess Scorned",
  "The Goddess Unleashed",
  "Ichimonji",
  "Lakishu's Blade",
  "The Princess",
  "Prismatic Eclipse",
  "Rebuke of the Vaal",
  "Redbeak",
  "Rigwald's Command",
  "Aurumvorax",
  "Chitus' Needle",
  "Fidelitas' Spike",
  "The Goddess Bound",
  "Doomsower",
  "Edge of Madness",
  "Oro's Sacrifice",
  "Queen's Decree",
  "Rigwald's Charge",
  "Shiversting",
  "Terminus Est",
  "Agnerod East",
  "Agnerod North",
  "Agnerod South",
  "Agnerod West",
  "The Blood Thorn",
  "Dying Breath",
  "Femurs of the Saints",
  "Fencoil",
  "Hegemony's Era",
  "Pillar of the Caged God",
  "Pledge of Hands",
  "Realmshaper",
  "The Searing Touch",
  "Sire of Shards",
  "The Stormheart",
  "Taryn's Shiver",
  "Tremor Rod",
  "The Whispering Ice",
  "Abberath's Horn",
  "Apep's Rage",
  "Eclipse Solaris",
  "Lifesprig",
  "Midnight Bargain",
  "Moonsorrow",
  "Piscator's Vigil",
  "Reverberation Rod",
  "Storm Prison",
  "Twyzel",
  "Void Battery",
  "Wyrmsign",
  "Obliteration"
]

def isUnique(input):
  return len([name.upper() for name in UNIQUE_LIST if name.upper() == input.upper()]) > 0